"""Ho:YAG structured-light simulation tools."""

from .propagation import (
    Grid2D,
    angular_spectrum_propagate,
    gaussian_beam,
    hermite_gaussian,
    laguerre_gaussian,
    apply_phase_mask,
    optical_power,
    normalize_power,
)
from .temporal import (
    TimeGrid,
    apply_gdd,
    apply_gvd,
    combine_spatial_temporal,
    gaussian_temporal_envelope,
    normalize_temporal_energy,
    propagate_spatiotemporal,
    pulse_intensity_fwhm_s,
    spatiotemporal_energy,
    temporal_energy,
)
from .spectroscopy import (
    pump_absorption_cross_section_295K,
    effective_pump_absorption_cross_section_295K,
)
from .populations import (
    HoYAGFourLevelParams,
    ground_state_populations,
    stimulated_rates_from_intensity,
    four_level_rhs,
    pump_absorption_coefficient_m1,
    laser_gain_coefficient_m1,
    scale_pulse_to_energy,
    integrate_populations,
    pump_material_step,
    propagate_single_pulse_hoyag,
)

__all__ = [
    "Grid2D",
    "angular_spectrum_propagate",
    "gaussian_beam",
    "hermite_gaussian",
    "laguerre_gaussian",
    "apply_phase_mask",
    "optical_power",
    "normalize_power",
    "TimeGrid",
    "apply_gdd",
    "apply_gvd",
    "combine_spatial_temporal",
    "gaussian_temporal_envelope",
    "normalize_temporal_energy",
    "propagate_spatiotemporal",
    "pulse_intensity_fwhm_s",
    "spatiotemporal_energy",
    "temporal_energy",
    "pump_absorption_cross_section_295K",
    "effective_pump_absorption_cross_section_295K",
    "HoYAGFourLevelParams",
    "ground_state_populations",
    "stimulated_rates_from_intensity",
    "four_level_rhs",
    "pump_absorption_coefficient_m1",
    "laser_gain_coefficient_m1",
    "scale_pulse_to_energy",
    "integrate_populations",
    "pump_material_step",
    "propagate_single_pulse_hoyag",
]
